//! The hooks are exercised here, because nothing else exercises them.
//!
//! `.githooks/` enforces compile-before-push and blocks agent directories from
//! reaching the remote. Until this file existed it appeared in no workflow and
//! no test: it was verified once, by hand, by the person who wrote it. If
//! someone broke `pre-push`, nothing would notice — and the failure mode is
//! silence, which is the shape this whole effort exists to remove.
//!
//! A gate nobody checks is a claim, not a control.

use std::fs;
use std::path::Path;
use std::process::Command;

fn hook(name: &str) -> String {
    fs::read_to_string(Path::new(".githooks").join(name))
        .unwrap_or_else(|e| panic!(".githooks/{name} must be readable: {e}"))
}

/// Runs a hook in a scratch directory with a scratch index, so nothing here can
/// disturb the real repository.
fn run_hook_in(dir: &Path, name: &str, stdin: &str) -> (i32, String) {
    let out = Command::new("bash")
        .arg(fs::canonicalize(Path::new(".githooks").join(name)).expect("hook path"))
        .arg(stdin)
        .current_dir(dir)
        .output()
        .expect("hook runs");
    (
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout).to_string() + &String::from_utf8_lossy(&out.stderr),
    )
}

#[test]
fn commit_msg_refuses_a_non_conventional_message_and_accepts_a_conventional_one() {
    let dir = tempfile::tempdir().expect("tempdir");
    let msg = dir.path().join("MSG");

    fs::write(&msg, "just some words\n").unwrap();
    let (code, out) = run_hook_in(dir.path(), "commit-msg", msg.to_str().unwrap());
    assert_eq!(code, 1, "a non-conventional message must be refused: {out}");

    fs::write(&msg, "fix(scope): a real summary\n").unwrap();
    let (code, out) = run_hook_in(dir.path(), "commit-msg", msg.to_str().unwrap());
    assert_eq!(code, 0, "a conventional message must pass: {out}");

    // A merge commit is generated by git, not typed by a person.
    fs::write(&msg, "Merge branch 'main' into feature\n").unwrap();
    let (code, _) = run_hook_in(dir.path(), "commit-msg", msg.to_str().unwrap());
    assert_eq!(code, 0, "generated merge messages must not be refused");
}

#[test]
fn every_hook_honours_the_documented_escape_hatch() {
    // A hook with no deliberate bypass gets disabled wholesale the first time it
    // is wrong, and --no-verify becomes habit. The escape must be greppable.
    for name in ["pre-commit", "pre-push", "commit-msg"] {
        assert!(
            hook(name).contains("ANVIL_SKIP_HOOKS"),
            ".githooks/{name} has no deliberate bypass"
        );
    }
}

#[test]
fn pre_push_checks_clippy_and_not_only_compilation() {
    // This hook shipped checking `cargo check` alone and let a `-D warnings`
    // failure reach the remote. A gate that passes what the next gate fails
    // teaches the reader that green means safe.
    let src = hook("pre-push");
    assert!(
        src.contains("cargo check"),
        "pre-push must check compilation"
    );
    assert!(
        src.contains("clippy"),
        "pre-push must check clippy: CI treats -D warnings as fatal, so a hook that \
         ignores them passes what CI will fail"
    );
}

#[test]
fn pre_push_does_not_read_a_command_status_through_a_pipeline() {
    // `cmd | tail` returns tail's status. Relying on `pipefail` to rescue that is
    // how the first version of the clippy check would have swallowed the very
    // failure it exists to catch.
    let src = hook("pre-push");
    let clippy_line = src
        .lines()
        .find(|l| l.contains("cargo clippy"))
        .expect("a clippy invocation");
    assert!(
        !clippy_line.contains('|'),
        "clippy's exit status is read through a pipeline, which discards it: {clippy_line}"
    );
}

#[test]
fn pre_commit_names_every_agent_directory_that_has_been_found_tracked() {
    // Each of these was found tracked in a real repository. A guard listing only
    // the ones we remembered is how .omx survived the first sweep.
    let src = hook("pre-commit");
    for dir in [
        "claude", "codex", "cursor", "grok", "agents", "beads", "omc", "omx",
    ] {
        assert!(src.contains(dir), "pre-commit does not mention '{dir}'");
    }
}
