//! Lane `supply-chain-reads-the-lockfile`: two gates that claimed to audit a
//! dependency graph and never opened one.
//!
//! # The defect, restated from source
//!
//! `zero_day_status` publishes "Autonomous upstream RustSec/CVE patch
//! synthesis". Its evaluation was
//!
//!     let active_advisories = vec![];
//!     let detected = self.listener.reconcile_advisories(&diff_ctx.diff_content, &active_advisories);
//!     let is_clean = detected.is_empty();
//!
//! An empty advisory list makes the loop inside `reconcile_advisories` execute
//! zero times, so `detected` is empty on every input and `is_clean` is `true`
//! on every pull request. The same shape as the two literals fixed in #63,
//! spelled `vec![]` instead of `true`. It also never read a lockfile: the
//! matcher's parameter is named `lockfile_content` and the caller handed it
//! `diff_ctx.diff_content`. Nothing in the module writes a patch, so the
//! "synthesis" half has no implementation at all and the gate now abstains.
//!
//! `supply_chain_status` publishes "Dependency audit, Syft CycloneDX SBOM &
//! provenance". It text-scanned the diff for six package names. No lockfile, no
//! advisory database, no SBOM, and `slsa_provenance_generated` was assigned
//! `is_secure` -- a self-attested SLSA level, which the SLSA build track does
//! not permit at L2 in any case (the hosted platform must be the signer).
//!
//! # What replaces it
//!
//! `SupplyChainGuard::audit_supply_chain` reads `Cargo.lock` from the working
//! tree, resolves every `[[package]]` entry, and queries OSV.dev's
//! `/v1/querybatch` endpoint -- the same database `osv-scanner` uses -- through
//! the bounded executor. A real advisory against a real locked version fails
//! the gate; every way the query can fail reports `NotMeasured`.
//!
//! # Why every test here is offline
//!
//! A gate whose test suite reaches api.osv.dev is a gate whose test suite is a
//! network monitor. The transport is one function, `post_json`, and it is
//! exercised against programs that are not curl. Everything that decides a
//! verdict -- lockfile parsing, payload construction, response parsing, the
//! pass/fail rule -- is pure and is driven from fixtures.

use anvil::git_manager::PrDiffContext;
use anvil::pre_merge_guard::report::GateStatus;
use anvil::supply_chain_guard::osv_stream::{self, OsvAdvisoryStream};
use anvil::supply_chain_guard::{LockedPackage, SupplyChainGuard};
use anvil::zero_day_patcher::ZeroDayAutoPatcher;
use std::path::Path;
use std::time::Duration;

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/// A minimal but real `Cargo.lock`, v4, three packages.
const LOCKFILE: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anvil"
version = "0.1.0"
dependencies = ["time"]

[[package]]
name = "time"
version = "0.1.44"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6db9e6914ab8b1ae1c260a4ae7a49b6c5611b40328a735b21862567685e73255"

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5f0e2c6ed6606019b4e29e69dbaba95b11854410e5347d525002456dbbb786b6"
"#;

/// An OSV `/v1/querybatch` response for the three packages above, in which the
/// second carries RUSTSEC-2020-0071 (the real `time` segfault advisory).
///
/// Batch results are deliberately minimal at OSV -- `id` and `modified` only --
/// which is why nothing here parses a severity it was not sent.
const BATCH_HIT: &str = r#"{"results":[
  {},
  {"vulns":[{"id":"RUSTSEC-2020-0071","modified":"2023-11-08T04:03:56.987Z"},
            {"id":"GHSA-wcg3-cvx6-7396","modified":"2023-11-08T04:03:56.987Z"}]},
  {"vulns":[]}
]}"#;

/// The same three packages, all clean. OSV returns an empty object per query
/// rather than omitting the entry.
const BATCH_CLEAN: &str = r#"{"results":[{},{"vulns":[]},{}]}"#;

fn packages() -> Vec<LockedPackage> {
    SupplyChainGuard::parse_lockfile(LOCKFILE).expect("the fixture lockfile parses")
}

fn ctx(work_dir: &Path) -> PrDiffContext {
    PrDiffContext {
        repo: "oyatie/anvil".to_string(),
        pr_number: 1,
        base_branch: "main".to_string(),
        base_sha: "aaa".to_string(),
        head_sha: "bbb".to_string(),
        previous_head_sha: None,
        repo_working_dir: anvil::git_manager::SubjectRoot::asserted(
            work_dir.to_path_buf(),
            anvil::git_manager::Uncloned::TestFixture,
        ),
        diff_content: "+ time = \"0.1.44\"\n".to_string(),
        changed_files: vec!["Cargo.toml".to_string()],
        is_incremental: false,
    }
}

fn assert_not_measured(status: &GateStatus, gate_id: &str, must_mention: &[&str]) {
    let GateStatus::NotMeasured {
        gate_id: id,
        reason,
    } = status
    else {
        panic!("expected {gate_id} to report NotMeasured, got {status:?}");
    };
    assert_eq!(id, gate_id, "NotMeasured must name its own gate");
    let lower = reason.to_lowercase();
    for needle in must_mention {
        assert!(
            lower.contains(&needle.to_lowercase()),
            "the reason must say what was missing; {needle:?} is absent from {reason:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// Lockfile resolution -- the input the gate never read
// ---------------------------------------------------------------------------

#[test]
fn every_locked_package_is_resolved_with_its_exact_version() {
    let pkgs = packages();
    assert_eq!(pkgs.len(), 3, "three [[package]] tables, three packages");
    assert_eq!(pkgs[1].name, "time");
    assert_eq!(
        pkgs[1].version, "0.1.44",
        "the exact locked version is what an advisory range is matched against; \
         a requirement from Cargo.toml is not"
    );
}

#[test]
fn a_malformed_lockfile_is_an_error_not_an_empty_package_list() {
    // An empty Vec would sail through the whole gate as "nothing vulnerable",
    // which is precisely how `vec![]` made the zero-day gate unfailable.
    let err = SupplyChainGuard::parse_lockfile("[[package]\nname = ")
        .expect_err("a truncated TOML table is not a lockfile");
    assert!(
        !err.trim().is_empty(),
        "the parse failure must carry a reason a reader can act on"
    );
}

#[test]
fn a_lockfile_with_no_packages_is_an_error_not_a_clean_audit() {
    let err = SupplyChainGuard::parse_lockfile("version = 4\n")
        .expect_err("a lockfile listing nothing audits nothing");
    assert!(err.to_lowercase().contains("package"));
}

// ---------------------------------------------------------------------------
// The OSV query -- built, and parsed, without touching the network
// ---------------------------------------------------------------------------

#[test]
fn the_batch_payload_asks_about_every_locked_package_by_name_and_version() {
    let payload = OsvAdvisoryStream::build_batch_payload(&packages());
    let json: serde_json::Value = serde_json::from_str(&payload).expect("payload is JSON");
    let queries = json["queries"].as_array().expect("queries array");

    assert_eq!(
        queries.len(),
        3,
        "one query per locked package; a batch shorter than the lockfile leaves \
         packages unaudited while reporting on the ones it did send"
    );
    assert_eq!(queries[1]["package"]["name"], "time");
    assert_eq!(queries[1]["version"], "0.1.44");
    assert_eq!(
        queries[1]["package"]["ecosystem"], "crates.io",
        "OSV keys Rust advisories under the crates.io ecosystem; any other \
         string matches nothing and returns an empty, reassuring result"
    );
}

#[test]
fn an_advisory_against_a_locked_version_is_attributed_to_that_package() {
    let hits = OsvAdvisoryStream::parse_batch_response(BATCH_HIT, &packages())
        .expect("a well-formed batch response parses");

    assert_eq!(
        hits.len(),
        1,
        "one of the three packages carries advisories"
    );
    assert_eq!(hits[0].name, "time");
    assert_eq!(hits[0].version, "0.1.44");
    assert_eq!(
        hits[0].advisory_ids,
        vec!["RUSTSEC-2020-0071", "GHSA-wcg3-cvx6-7396"],
        "every advisory id is carried through, so the scorecard names what to fix"
    );
}

#[test]
fn a_response_clean_for_every_package_finds_nothing() {
    let hits = OsvAdvisoryStream::parse_batch_response(BATCH_CLEAN, &packages())
        .expect("a clean batch response parses");
    assert!(hits.is_empty());
}

#[test]
fn a_response_body_that_is_not_json_is_an_error_not_a_clean_audit() {
    // A proxy interstitial, an HTML error page, or a truncated body. Every one
    // of them deserialises to "no vulns" if the failure is swallowed.
    for body in ["", "<html>502 Bad Gateway</html>", "{\"results\":"] {
        assert!(
            OsvAdvisoryStream::parse_batch_response(body, &packages()).is_err(),
            "body {body:?} must not parse as an advisory-free result"
        );
    }
}

#[test]
fn a_result_list_shorter_than_the_query_list_is_an_error() {
    // OSV pairs results to queries positionally. A short list silently shifts
    // every advisory onto the wrong package, and clears the tail.
    let err = OsvAdvisoryStream::parse_batch_response(r#"{"results":[{},{}]}"#, &packages())
        .expect_err("two results cannot answer three queries");
    assert!(
        err.contains('2') && err.contains('3'),
        "the error must state both counts so the mismatch is legible: {err}"
    );
}

/// Catches: a truncated advisory list published as though it were the answer.
/// OSV paginates a batch result past its own vulnerability thresholds and hands
/// back a `next_page_token`. Deserialising only `vulns` dropped it silently, so
/// the gate would name the first page of advisories and nothing would say the
/// rest existed -- on a gate whose entire value is naming what to fix.
#[test]
fn a_paginated_batch_is_an_error_not_a_shorter_advisory_list() {
    let body = r#"{"results":[{"vulns":[{"id":"RUSTSEC-2020-0071"}],
                   "next_page_token":"ct1"},{},{}]}"#;
    let err = OsvAdvisoryStream::parse_batch_response(body, &packages())
        .expect_err("a paginated result cannot be read as the complete answer");
    assert!(
        err.contains("incomplete"),
        "the error must say the advisory list is incomplete: {err}"
    );
}

/// Catches: the abstention above swallowing the ordinary case. Every clean and
/// every complete result carries no token, and those must still parse.
#[test]
fn an_unpaginated_batch_still_parses() {
    let body = r#"{"results":[{"vulns":[{"id":"RUSTSEC-2020-0071"}]},{},{}]}"#;
    let found = OsvAdvisoryStream::parse_batch_response(body, &packages())
        .expect("a complete batch parses");
    assert_eq!(found.len(), 1);
}

// ---------------------------------------------------------------------------
// The HTTP status curl reports -- rate limits, outages, and a missing status
// ---------------------------------------------------------------------------

#[test]
fn only_a_200_yields_a_body() {
    let body = osv_stream::body_of("{\"results\":[]}\n200").expect("200 yields its body");
    assert_eq!(body, "{\"results\":[]}");
}

#[test]
fn a_rate_limited_or_failed_request_is_an_error_not_an_empty_body() {
    // 429 is the one that matters: OSV publishes no quota, so a busy runner
    // finding out by being throttled must abstain rather than certify.
    for code in ["429", "400", "500", "503"] {
        let err = osv_stream::body_of(&format!("{{\"results\":[]}}\n{code}"))
            .expect_err("a non-200 response is not a clean audit");
        assert!(
            err.contains(code),
            "the reason must name the status the runner actually got: {err}"
        );
    }
}

#[test]
fn output_carrying_no_status_code_is_an_error() {
    // curl replaced by something that is not curl, or killed before `-w` ran.
    assert!(osv_stream::body_of("").is_err());
    assert!(osv_stream::body_of("just a body, no trailing status").is_err());
}

// ---------------------------------------------------------------------------
// The transport -- every way the subprocess itself can fail
// ---------------------------------------------------------------------------

/// A budget these fixtures are not measuring.
///
/// They are about the transport's answer: a 200 returned verbatim, a non-zero
/// exit reported, a missing status trailer refused. The deadline is incidental,
/// and at five seconds it was not incidental enough -- under a full-suite run
/// the machine took longer than that to spawn a two-line shell script, and both
/// fixtures failed with
///
///     curl OSV querybatch timed out after 5s
///
/// which is the transport reporting a timeout correctly and the fixture
/// measuring the load average. Observed twice, and never reproducible in
/// isolation, which is what a wall-clock dependency looks like from the outside.
///
/// The deadline itself is pinned by
/// `a_request_that_outlives_its_budget_is_killed_and_reported`, which builds a
/// `sleep` that genuinely outlives its budget. Nothing here is weakened by
/// giving these four room.
const NOT_A_DEADLINE_TEST: Duration = Duration::from_secs(120);

/// A program that answers exactly like curl -- body, newline, status trailer --
/// and exits with `code`. The only way to exercise the transport's success path
/// and its exit-code handling without making a network request.
#[cfg(unix)]
fn fake_curl(dir: &Path, body: &str, http: &str, code: u8) -> String {
    use std::os::unix::fs::PermissionsExt;
    // The raw executor admits only the finite `curl` tool name; putting the
    // fixture at that basename exercises the same capability without opening
    // an arbitrary-program test escape hatch.
    let path = dir.join("curl");
    std::fs::write(
        &path,
        format!("#!/bin/sh\nprintf '%s\\n%s' '{body}' '{http}'\nexit {code}\n"),
    )
    .expect("write fake curl");
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).expect("chmod");
    path.to_string_lossy().into_owned()
}

/// The transport's one success path, offline.
#[cfg(unix)]
#[tokio::test]
async fn a_two_hundred_response_is_returned_verbatim() {
    let dir = tempfile::tempdir().expect("tempdir");
    let program = fake_curl(dir.path(), r#"{"results":[{}]}"#, "200", 0);

    let body = osv_stream::post_json(
        &program,
        osv_stream::OSV_BATCH_URL,
        "{}",
        NOT_A_DEADLINE_TEST,
    )
    .await
    .expect("a 200 with a body is an answer");
    assert_eq!(body, r#"{"results":[{}]}"#);
}

/// Catches: dropping the exit-code check.
///
/// The first version of this test ran `false`, which exits 1 AND writes
/// nothing -- so it stayed green with the exit-code guard deleted, because the
/// empty output failed the status-trailer check instead. A curl that dies after
/// writing a plausible body -- a connection reset mid-transfer, `--max-time`
/// firing on a partial response -- is the case that needs the guard, and a
/// mutation survived until this test was written.
#[cfg(unix)]
#[tokio::test]
async fn a_nonzero_exit_is_an_error_even_when_the_body_looks_like_an_answer() {
    let dir = tempfile::tempdir().expect("tempdir");
    let program = fake_curl(dir.path(), r#"{"results":[{},{},{}]}"#, "200", 7);

    let err = osv_stream::post_json(
        &program,
        osv_stream::OSV_BATCH_URL,
        "{}",
        NOT_A_DEADLINE_TEST,
    )
    .await
    .expect_err("a transfer that died is not an advisory-free result");
    assert!(
        err.contains('7'),
        "the reason must name the exit status the runner saw: {err}"
    );
}

#[tokio::test]
async fn a_missing_curl_is_an_error_the_gate_can_report() {
    let err = osv_stream::post_json(
        "/anvil-there-is-no-such-directory/curl",
        osv_stream::OSV_BATCH_URL,
        "{}",
        NOT_A_DEADLINE_TEST,
    )
    .await
    .expect_err("a program that does not exist cannot answer");
    assert!(!err.trim().is_empty());
}

#[tokio::test]
async fn a_nonzero_exit_is_an_error_the_gate_can_report() {
    let dir = tempfile::tempdir().expect("tempdir");
    let program = fake_curl(dir.path(), "", "000", 1);
    let err = osv_stream::post_json(
        &program,
        osv_stream::OSV_BATCH_URL,
        "{}",
        NOT_A_DEADLINE_TEST,
    )
    .await
    .expect_err("a non-zero exit is not a clean audit");
    assert!(!err.trim().is_empty());
}

// ---------------------------------------------------------------------------
// The verdict -- can fail, can pass, and abstains on absent evidence
// ---------------------------------------------------------------------------

#[test]
fn a_lockfile_carrying_an_advisory_fails_the_gate() {
    let pkgs = packages();
    let hits = OsvAdvisoryStream::parse_batch_response(BATCH_HIT, &pkgs).expect("parses");
    let report = SupplyChainGuard::report(&pkgs, Ok(hits));

    let GateStatus::Failed(reason) = &report.status else {
        panic!("a locked version with a live advisory must fail: {report:?}");
    };
    assert!(
        reason.contains("time")
            && reason.contains("0.1.44")
            && reason.contains("RUSTSEC-2020-0071"),
        "the failure must name the package, the locked version and the advisory: {reason}"
    );
    assert_eq!(report.audited_packages, 3);
}

#[test]
fn a_clean_lockfile_passes_the_gate() {
    let pkgs = packages();
    let report = SupplyChainGuard::report(&pkgs, Ok(Vec::new()));

    assert!(
        matches!(report.status, GateStatus::Passed),
        "a resolved lockfile with no advisory against any locked version is a \
         measured pass, not an abstention: {report:?}"
    );
    assert_eq!(
        report.audited_packages, 3,
        "the count published is the number of packages queried, not the number \
         of files the pull request touched"
    );
}

#[test]
fn an_unreachable_advisory_database_is_not_measured_and_never_a_pass() {
    let report = SupplyChainGuard::report(&packages(), Err("curl exited 6".to_string()));

    assert_not_measured(&report.status, "supply_chain_status", &["curl exited 6"]);
    assert!(
        !report.status.is_measured(),
        "an absent advisory feed blocks admission through unmeasured_gates; it \
         must not be laundered into a pass"
    );
}

// ---------------------------------------------------------------------------
// The gate end to end, on the paths that never reach the network
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_working_tree_with_no_cargo_lock_is_not_measured() {
    let work = tempfile::tempdir().expect("tempdir");
    let report = SupplyChainGuard::new()
        .audit_supply_chain(work.path(), &ctx(work.path()))
        .await
        .expect("the gate answers");

    assert_not_measured(&report.status, "supply_chain_status", &["Cargo.lock"]);
}

#[tokio::test]
async fn an_unparseable_cargo_lock_is_not_measured() {
    let work = tempfile::tempdir().expect("tempdir");
    std::fs::write(work.path().join("Cargo.lock"), "[[package]\nname = ").expect("write");

    let report = SupplyChainGuard::new()
        .audit_supply_chain(work.path(), &ctx(work.path()))
        .await
        .expect("the gate answers");

    assert_not_measured(&report.status, "supply_chain_status", &["Cargo.lock"]);
}

#[tokio::test]
async fn the_gate_publishes_no_sbom_and_no_provenance_claim() {
    // The row said "Syft CycloneDX SBOM & provenance" while the report field
    // `slsa_provenance_generated` was assigned the audit's own boolean. Nothing
    // generated either artefact, and a build script cannot self-attest SLSA L2
    // regardless: the build track requires the hosted platform to be the signer.
    let work = tempfile::tempdir().expect("tempdir");
    let report = SupplyChainGuard::new()
        .audit_supply_chain(work.path(), &ctx(work.path()))
        .await
        .expect("the gate answers");

    let json = serde_json::to_value(&report).expect("serialises");
    let fields: Vec<&String> = json.as_object().expect("object").keys().collect();
    for claim in ["slsa", "sbom", "provenance", "cyclonedx"] {
        assert!(
            !fields.iter().any(|f| f.to_lowercase().contains(claim)),
            "the report still publishes a {claim} field it does not produce: {fields:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// The zero-day gate, which abstains
// ---------------------------------------------------------------------------

#[test]
fn the_zero_day_gate_reports_not_measured_because_it_synthesises_no_patch() {
    let work = tempfile::tempdir().expect("tempdir");
    let report = ZeroDayAutoPatcher::new()
        .evaluate_zero_day_patches(work.path(), &ctx(work.path()))
        .expect("the gate answers");

    assert_not_measured(&report.status, "zero_day_status", &["patch"]);
}

#[test]
fn the_zero_day_gate_abstains_on_a_diff_that_would_previously_have_passed() {
    // The old evaluation was `vec![]` -> `detected.is_empty()` -> `is_clean`,
    // so a diff introducing a known-vulnerable version was certified clean.
    // Nothing about the diff may produce a pass now.
    let work = tempfile::tempdir().expect("tempdir");
    let mut d = ctx(work.path());
    d.diff_content = "+time = \"0.1.44\"\n+openssl = \"0.10.30\"\n".to_string();

    let report = ZeroDayAutoPatcher::new()
        .evaluate_zero_day_patches(work.path(), &d)
        .expect("the gate answers");

    assert!(
        !report.status.is_measured(),
        "the zero-day gate reads no advisory feed and writes no patch; a diff \
         cannot make it pass: {report:?}"
    );
}

// ---------------------------------------------------------------------------
// The wiring between the gate and the client that was left dead
// ---------------------------------------------------------------------------

/// Catches: the client goes dead again.
///
/// Every other test in this file is offline, which means every end-to-end test
/// answers before the transport is reached. That leaves one mutation alive:
/// replacing the query with `Ok(Vec::new())` keeps the lockfile parsing, keeps
/// all three abstentions, and turns the audit back into a constant -- the exact
/// state `query_package` was found in. Written, correct, and called by nobody.
///
/// A behavioural test cannot see it without a network request, so this reads
/// the wire itself. `production_source` drops the `#[cfg(test)]` half: a call
/// inside a test module is not a call in the gate.
#[test]
fn the_gate_asks_the_advisory_database_rather_than_answering_from_itself() {
    let src = production_source("src/supply_chain_guard");
    assert!(
        src.contains("OsvAdvisoryStream::query_batch(&packages).await"),
        "the audit no longer queries the advisory database, so its verdict is \
         whatever the code substituted for the query"
    );

    let transport = production_source("src/supply_chain_guard/osv_stream");
    assert!(
        transport.contains("post_json(CURL, OSV_BATCH_URL, &payload, OSV_BUDGET).await"),
        "the query no longer goes through the bounded executor with a budget"
    );
    assert!(
        // `run_bounded` and not `run_bounded_for(cmd, budget`: the invariant is
        // that the subprocess is bounded, and `run_bounded(cmd, ExecClass::Api,
        // ..)` satisfies it too. Pinning one spelling would turn this guard RED
        // for a change that breaks nothing.
        transport.contains("run_bounded"),
        "a per-PR network call outside the bounded executor has no deadline \
         (invariant I5)"
    );
    assert!(
        // The exact argument, not the mention: `body_of`'s own doc comment
        // names `%{http_code}`, so a looser needle stayed green with the
        // argument deleted and a mutation survived.
        transport.contains(r#""\n%{http_code}""#),
        "without the status trailer curl -s hides a 429 and the throttled \
         response parses as an advisory-free result"
    );
}

/// Keyed to the module rather than to a path. Splitting an oversized file into
/// a directory is routine here, and a path-keyed read finds nothing the day it
/// happens: blind rather than failing, because a scan that reads nothing
/// reports nothing wrong. `module_source` reads whichever form the module
/// takes, strips its test modules, and refuses one that is absent.
fn production_source(module: &str) -> String {
    anvil::source_scan::paths::module_source(module, Path::new(env!("CARGO_MANIFEST_DIR")))
}
